services:
  db:
    image: mysql:8.0
    container_name: myproject_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3308:3308"

  web:
    build: .
    container_name: myproject_web
    command: >
      sh -c "python -m pip install -r requirements.txt && 
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:9191"
    volumes:
      - .:/app
    ports:
      - "9191:9191"
    depends_on:
      - db
    environment:
      - DATABASE_NAME=mydatabase
      - DATABASE_USER=root
      - DATABASE_PASSWORD=rootpassword
      - DATABASE_HOST=db
      - DATABASE_PORT=3308

volumes:
  db_data:
